Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder "./files_to_download", "/vagrant_data"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y python3-pip
    apt-get install -y libpq-dev
    pip3 install psycopg2 Django
  SHELL
end